#!/bin/bash -x
# qsub -l nodes=1 -q diag  -l walltime=00:20:00 -l filesystems=gila -A  Aurora_deployment -I 
# https://github.com/oneapi-src/oneCCL/tree/master/examples/benchmark/src

#PBS -A Aurora_deployment
#PBS -k doe

module list
module use /soft/modulefiles
module load frameworks/2023.12.15.001 
# module load frameworks
# module load spack 
# module load cmake
# module load autoconf
# cmake .. -DCMAKE_C_COMPILER=icx -DCMAKE_CXX_COMPILER=icpx -DCOMPUTE_BACKEND=dpcpp

cd $PBS_O_WORKDIR
echo Jobid: $PBS_JOBID
echo Running on nodes `cat $PBS_NODEFILE`

NNODES=`wc -l < $PBS_NODEFILE`
RANKS_PER_NODE=12          # Number of MPI ranks per node
NRANKS=$(( NNODES * RANKS_PER_NODE ))
echo "NUM_OF_NODES=${NNODES}  TOTAL_NUM_RANKS=${NRANKS}  RANKS_PER_NODE=${RANKS_PER_NODE}"
     
CPU_BINDING=list:1-2:9-10:17-18:25-26:33-34:41-42:52-53:60-61:68-69:76-77:84-85:92-93  
APP=/lus/gila/projects/CSC250STDM10_CNDA/kaushik/oneCCL/build2/_install/examples/benchmark/benchmark
STRACE_WRAPPER=/lus/gila/projects/CSC250STDM10_CNDA/kaushik/gitrepos/src-strace-analyser/strace-analyzer/strace-wrapper.sh


 
date 

# mpiexec  --np ${NRANKS} -ppn ${RANKS_PER_NODE} --cpu-bind  $CPU_BINDING  $APP  --max_elem_count 512  --coll allreduce -j off -i 1 -w 0  
# mpiexec  --np ${NRANKS} -ppn ${RANKS_PER_NODE} --cpu-bind  $CPU_BINDING  $APP  --max_elem_count 512  --coll allreduce -j off -i 1 -w 0   

# mkdir -p $PBS_O_WORKDIR/strace_1_$NNODES
# mkdir -p $PBS_O_WORKDIR/strace_2_$NNODES

# LOGDIR=$PBS_O_WORKDIR/strace_1_$NNODES mpiexec --env FI_CXI_DEFAULT_CQ_SIZE=16384  --env FI_CXI_OVFLOW_BUF_SIZE=8388608 --env FI_CXI_CQ_FILL_PERCENT=20 --np ${NRANKS} -ppn ${RANKS_PER_NODE} --cpu-bind  $CPU_BINDING  $STRACE_WRAPPER  $APP  --max_elem_count 512  --coll allreduce -j off -i 1 -w 0  --backend host
# LOGDIR=$PBS_O_WORKDIR/strace_2_$NNODES mpiexec --env FI_CXI_DEFAULT_CQ_SIZE=16384  --env FI_CXI_OVFLOW_BUF_SIZE=8388608 --env FI_CXI_CQ_FILL_PERCENT=20 --np ${NRANKS} -ppn ${RANKS_PER_NODE} --cpu-bind  $CPU_BINDING  $STRACE_WRAPPER  $APP  --max_elem_count 512  --coll allreduce -j off -i 1 -w 0  --backend host

# CCL_PROCESS_LAUNCHER=pmix CCL_ATL_TRANSPORT=mpi  or CCL_ZE_IPC_EXCHANGE=sockets  solves this sig 6 or 9 or 15 issues in future.

date
mpiexec --env FI_CXI_DEFAULT_CQ_SIZE=16384  --env FI_CXI_OVFLOW_BUF_SIZE=8388608 --env FI_CXI_CQ_FILL_PERCENT=20 --np ${NRANKS} -ppn ${RANKS_PER_NODE} --cpu-bind  $CPU_BINDING    $APP  --max_elem_count 512  --coll allreduce -j off -i 1 -w 0  --backend host
date
mpiexec --env FI_CXI_DEFAULT_CQ_SIZE=16384  --env FI_CXI_OVFLOW_BUF_SIZE=8388608 --env FI_CXI_CQ_FILL_PERCENT=20 --np ${NRANKS} -ppn ${RANKS_PER_NODE} --cpu-bind  $CPU_BINDING    $APP  --max_elem_count 512  --coll allreduce -j off -i 1 -w 0  --backend host

